[build]
  base = "frontEnd"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://login-app-6-bc9e.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
